name: countries_app
description: "Country details delivered through a native Flutter experience."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: 3.22.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  icons_launcher: ^2.1.7

flutter:
  uses-material-design: true

icons_launcher:
  image_path: "assets/launch_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true
